blank_issues_enabled: false
contact_links:
  - name: Zed Official Issue Tracker
    url: https://github.com/zed-industries/zed/issues
    about: Report issues with Zed functionality, features, crashes, or bugs (NOT build-related issues)
  - name: Zed Community Discord
    url: https://discord.gg/zed-community
    about: Get help and support for using Zed
  - name: Official Zed Downloads
    url: https://zed.dev/download
    about: Download official Windows builds of Zed (recommended for most users)
