name: Build

on:
  workflow_call:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: zed-industries/zed
      ref:
        description: Branch/tag/ref to build
        type: string
        required: true
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: zed-industries/zed
      ref:
        description: Branch/tag/ref to build
        type: string
        default: main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: cli
            build_path: crates/cli
            artifact: cli-release
            binary: cli.exe

          - name: editor-dx11
            build_path: .
            artifact: editor-dx11-release
            binary: zed.exe
            rustflags: ""

          - name: editor-opengl
            build_path: .
            artifact: editor-opengl-release
            binary: zed.exe
            rustflags: "--cfg gles"
      fail-fast: false

    steps:
      - name: Enable long paths in Git
        run: git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout Zed
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: zed

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.name }}-${{ hashFiles('**/Cargo.lock') }}
          workspaces: "zed -> target"

      - name: Install PSToml module
        shell: pwsh
        run: Install-Module -Name PSToml -Scope CurrentUser -Force

      - name: Setup rustflags
        shell: pwsh
        run: ./scripts/Parse-Rustflags.ps1 ${{ matrix.rustflags }}

      - name: Build ${{ matrix.name }}
        working-directory: zed/${{ matrix.build_path }}
        env:
          ZED_UPDATE_EXPLANATION: "Please use Scoop to update Zed."
        run: cargo b -r

      - name: Upload ${{ matrix.name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: zed/target/release/${{ matrix.binary }}
